import type { Fidelity } from '../../pipeline/events';

export function FidelityBadge({ fidelity, compact = false }: { fidelity: Fidelity; compact?: boolean }) {
  const real = fidelity === 'real';
  return (
    <span
      title={
        real
          ? 'Observed from the model or API in this run'
          : 'Generated by a deterministic simulator — not from this model'
      }
      className={
        'inline-flex items-center gap-1.5 rounded-full px-2 py-0.5 text-[10.5px] font-semibold uppercase tracking-[0.08em] ' +
        (real
          ? 'border border-ok/40 bg-ok/10 text-ok'
          : 'border border-dashed border-warn/50 bg-warn/10 text-warn')
      }
    >
      <span className={'h-1.5 w-1.5 rounded-full ' + (real ? 'bg-ok' : 'bg-warn')} />
      {compact ? (real ? 'Real' : 'Illus.') : real ? 'Real' : 'Illustrative'}
    </span>
  );
}

export function Kbd({ children }: { children: string }) {
  return (
    <kbd className="mono inline-flex h-5 min-w-5 items-center justify-center rounded border border-line-strong bg-surface-2 px-1 text-[10.5px] text-text-muted">
      {children}
    </kbd>
  );
}
